wif comments

diff --git a/.github/workflows/docs-build-publish-surge.yml b/.github/workflows/docs-build-publish-surge.yml
--- a/.github/workflows/docs-build-publish-surge.yml
+++ b/.github/workflows/docs-build-publish-surge.yml
@@ -1,15 +1,20 @@
 ---
-name: Ansible collection docs - post comment and publish to Surge
+name: Ansible collection docs - publish to Surge
 on:
   workflow_call:
     inputs:
       artifact-name:
-        description: The build artifact that contains the rendered HTML.
-        required: true
+        description: The build artifact that contains the rendered HTML. Required when action == 'publish'
+        required: false
         type: string
       surge-site-name:
-        description: The full surge site domain to publish to.
+        description: The full surge site domain to publish or teardown.
         required: true
+        type: string
+      action:
+        description: Action to perform. 'publish' to publish the site, 'teardown' to tear it down.
+        required: false
+        default: 'publish'
         type: string
     secrets:
       SURGE_TOKEN:
@@ -29,7 +34,14 @@ jobs:
           ${{ toJSON(inputs) }}
           EOF
 
+      - name: Check required
+        if: inputs.action == 'publish' && inputs.artifact-name == ''
+        run: |
+          echo "::error title=Missing artifact-name::action was 'publish' but artifact-name was not supplied."
+          exit 1
+
       - name: Retrieve rendered docs
+        if: inputs.action == 'publish'
         id: download
         uses: actions/download-artifact@v2
         with:
@@ -45,5 +57,11 @@ jobs:
         run: npm install -g surge
 
       - name: Publish site
+        if: inputs.action == 'publish'
         working-directory: html
         run: surge ./ "${{ inputs.surge-site-name }}" --token ${{ secrets.SURGE_TOKEN }}
+
+      - name: Teardown site
+        if: inputs.action == 'teardown'
+        run: surge teardown "${{ inputs.surge-site-name }}" --token ${{ secrets.SURGE_TOKEN }}
+        continue-on-error: true
